# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2919c76b65a69e3ee745d197a3edc1e7b465a5032730f0746bfa6e3bad97722eb19ecfb44ba081649a495bedcda3f7459ddc406ab35a211d2c2ed0561e516e2a

test:
  secret_key_base: 99ae32f31728cadb64915f59f86dca3c4ae0cdbbaf16df6a782f28b35d2496fbf5399247661cdc6e36de10256eb8d81ef911d4df1623b41aadc11b298395a2e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
